### ISSUE TITLE
104 Errors on UWP app build

### ISSUE THREAD

**Issue by DDR12** [dgkanatsios/AzureServicesForUnity#3]
Thank you for your efforts, much appreciated!
This is perfect and smooth in editor.
Trying to build a UWP app I got like 104 errors: here's a peak on some of them:

Full Log of all errors mostly because some APIs are no longer compatiable with UWP.
Which means we'll need to use #if NETFX_CORE

Part of Editor log: 
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\Utilities.cs(30,29): error CS1061: 'Type' does not contain a definition for 'IsGenericType' and no extension method 'IsGenericType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3709,28): error CS1061: 'MemberInfo' does not contain a definition for 'MemberType' and no extension method 'MemberType' accepting a first argument of type 'MemberInfo' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3722,28): error CS1061: 'MemberInfo' does not contain a definition for 'MemberType' and no extension method 'MemberType' accepting a first argument of type 'MemberInfo' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3631,82): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3654,33): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2441,38): error CS1501: No overload for method 'GetMethod' takes 5 arguments
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2446,30): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2448,69): error CS1061: 'ConstructorInfo' does not contain a definition for 'MethodHandle' and no extension method 'MethodHandle' accepting a first argument of type 'ConstructorInfo' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3057,60): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(3037,55): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2989,50): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2966,54): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2941,57): error CS1061: 'Type' does not contain a definition for 'IsValueType' and no extension method 'IsValueType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2898,56): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2880,52): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2563,26): error CS0234: The type or namespace name 'FormatterServices' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2533,26): error CS0234: The type or namespace name 'FormatterServices' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2507,26): error CS0234: The type or namespace name 'FormatterServices' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2484,26): error CS0234: The type or namespace name 'FormatterServices' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2463,26): error CS0234: The type or namespace name 'FormatterServices' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2414,58): error CS1061: 'Type' does not contain a definition for 'IsSubclassOf' and no extension method 'IsSubclassOf' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2369,54): error CS0117: 'Delegate' does not contain a definition for 'CreateDelegate'
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2213,61): error CS1061: 'Type' does not contain a definition for 'IsValueType' and no extension method 'IsValueType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(2069,61): error CS1061: 'Type' does not contain a definition for 'IsValueType' and no extension method 'IsValueType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(616,50): error CS1061: 'Type' does not contain a definition for 'IsValueType' and no extension method 'IsValueType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\AzureServicesForUnity\QueryHelpers\Other\PartialEvaluatorNoEmit.cs(616,77): error CS1061: 'Type' does not contain a definition for 'IsValueType' and no extension method 'IsValueType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by dgkanatsios** [comment]
Just did a quick check, apart from the UWP types missing (which could or could not be solved), there is also another issue which I've missed. I see some errors on the UnityWebRequest object, such as
_Assets\AzureServicesForUnity\EasyTables.cs(76,34): error CS1061: 'UnityWebRequest' does not contain a definition for 'Send' and no extension method 'Send' accepting a first argument of type 'UnityWebRequest' could be found (are you missing a using directive or an assembly reference?)_
Not sure if this can be resolved (UnityWebRequest is the core in the library), will keep searching.

**Comment by DDR12** [comment]
@dgkanatsios Even if you set (From player settings) .NET CORE to None, this would remove all Type errors but you'd still get he UnityWebRequest errors.
Note that setting .NET CORE to none will make the WACK test fail when submitting to store so, it has to use native UWP libraries or using the #if NETFX_CORE

I did find a work around, using REST API and ODATA queries but they're just painful to work with but I had no other option, what attracted me to this was it's plugin-less nature.

**Comment by dgkanatsios** [comment]
As mentioned [here](https://community.unity.com/t5/Windows/Compilation-errors-when-trying-to-build-for-UWP-windows10/m-p/2651326) UnityWebRequest works on 5.4 (still in Beta). Can you check? Let's solve this and then we'll check the Type related errors.

Moreover, can you run a quick check and run [this](https://github.com/dgkanatsios/AzureServicesForUnity/tree/b0e339c5e292aa6ece49c93531f7e60c0214005c) version and let me know whether the Type related errors still occur?

**Comment by dgkanatsios** [comment]
Fixed with version 0.0.12, I basically removed all the LINQ-to-OData query stuff, works now on UWP.
